FROM golang:1.21.4 AS build

WORKDIR /app

COPY . .

RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-w -s" -o project ./cmd/clean-project-exp/main.go

FROM scratch

COPY --from=build /app/project .

CMD ["./project"]